name: Prueba tokens

on:
  push:

jobs:
  comprobar-token:
    runs-on: self-hosted

    steps:
      - name: Comparar DEV_TOKEN con LOCAL_DEV_TOKEN
        shell: cmd
        env:
          DEV_TOKEN: ${{ secrets.DEV_TOKEN }}
        run: |
          if "%DEV_TOKEN%"=="%LOCAL_DEV_TOKEN%" (
            echo Los tokens coinciden
          ) else (
            echo Los tokens NO coinciden
            exit /b 1
          )
